### Basic Text Processing

In [1]:
#%% Getting a list of directory contents
import os
def gettextlist(directory_path):
    directory_textfiles=[]
    directory_nontextfiles=[]
    directory_nonfiles=[]
    # Process each item in the directory
    directory_contents=os.listdir(directory_path)
    for contentitem in directory_contents:
        temp_fullpath=os.path.join(directory_path, contentitem)
        # Non-files (e.g. subdirectories) are stored separately
        if os.path.isfile(temp_fullpath)==0:
            directory_nonfiles.append(contentitem)
        else:
            # Is this a non-text file (not ending in .txt)?
            if temp_fullpath.find('.txt')==-1:
                directory_nontextfiles.append(contentitem)
            else:
                 # This is a text file
                directory_textfiles.append(contentitem)
    return(directory_textfiles,directory_nontextfiles,directory_nonfiles)



In [7]:
mydirectory_path='D:/'
mydirectory_contentlists=gettextlist(mydirectory_path)

In [8]:
mydirectory_contentlists

([],
 ['0804-fundamentals-of-python-programming.pdf',
  '2008_Book_IntroductoryStatisticsWithR.pdf',
  '2008_Book_TimeSeriesAnalysis.pdf',
  '4Hypothesistestinginthemultipleregressionmodel.pdf',
  'An Introduction to Statistical Learning – with Application in R.pdf',
  'bayesianbook_problemsanswers_final.pdf',
  'bayesian_data_analysis.pdf',
  'casella_berger_statistical_inference1.pdf',
  'dimensionality-reduction.pdf',
  'ethiopic_digit_recognition.pdf',
  'Introducing Monte Carlo Methods with R.pdf',
  'lab2bayes20soln.pdf',
  'Learning Spark  Lightning-Fast Big Data Analysis .pdf',
  'Linux Basics Course - Study Guide.pdf',
  'linux-commands-handbook.pdf',
  'ML_cheatsheets.pdf',
  'Probability and Statistics for Data Science.pdf',
  'R for Data Science- Import, Tidy, Transform, Visualize, and Model Data.pdf',
  'R_for_dummies.pdf',
  'scala-for-the-impatient-2nd-edition.pdf',
  'Spark_ The Definitive Guide_ Big Data Processing Made Simple ( PDFDrive ).pdf',
  'Statistical_analysis

In [11]:
mydirectory_contentlists[2]

['$RECYCLE.BIN',
 'AWS',
 'DR',
 'information_searching',
 'Intro_pattern_recog_machine_learning',
 'Machine+Learning+A-Z+(Codes+and+Datasets)',
 'Power BI',
 'PRML',
 'statistical_inference',
 'System Volume Information',
 'Tunde_Java']

In [2]:
#%% Basic file crawler
def basicfilecrawler(directory_path):
 # Store filenames read and their text content
    num_files_read=0
    crawled_filenames=[]
    crawled_texts=[]
    directory_contentlists=gettextlist(directory_path)
     # In this basic crawled we just process text files
     # and do not handle subdirectories
    directory_textfiles=directory_contentlists[0]
    for contentitem in directory_textfiles:
        print('Reading file:')
        print(contentitem)
        # Open the file and read its contents
        temp_fullpath=os.path.join(directory_path, contentitem)
        temp_file=open(temp_fullpath,'r',encoding='utf-8',errors='ignore')
        temp_text=temp_file.read()
        temp_file.close()
        # Store the read filename and content
        crawled_filenames.append(contentitem)
        crawled_texts.append(temp_text)
        num_files_read=num_files_read+1
    return(crawled_filenames,crawled_texts)


In [3]:

mycrawled_filenames_and_texts=basicfilecrawler('C:/Users/tunde/Documents/R/TSA')
mycrawled_filenames=mycrawled_filenames_and_texts[0]
mycrawled_texts=mycrawled_filenames_and_texts[1]

Reading file:
Beverage.txt
Reading file:
deaths.txt


In [5]:
len(mycrawled_texts)

2

In [7]:
mycrawled_texts

['17\n19\n20\n15\n13\n14\n14\n14\n14\n11\n16\n19\n23\n18\n17\n20\n20\n18\n14\n16\n21\n24\n15\n16\n20\n14\n16\n25.5\n25.8\n26\n26\n29\n20\n18\n16\n22\n22\n16\n19\n17\n17\n19\n20\n24\n28\n36\n20\n14\n18\n27\n29\n36\n29\n27\n30\n38\n50\n24\n25\n30\n31\n37\n41\n36\n32\n47\n42\n37\n34\n36\n43\n55\n64\n79\n59\n47\n48\n49\n45\n53\n55\n55\n54\n56\n52\n76\n113\n68\n59\n74\n78\n69\n78\n73\n88\n98\n109\n106\n87\n77\n77\n63\n70\n70\n63\n61\n66\n78\n93\n97\n77\n83\n81\n82\n78\n75\n80\n87\n72\n65\n74\n91\n115\n99\n99\n115\n101\n90\n95\n108\n147\n112\n108\n99\n96\n102\n105\n114\n103\n98\n103\n101\n110\n109\n98\n84\n90\n120\n124\n136\n120\n135\n100\n70\n60\n72\n70\n71\n94\n95\n110\n154\n116\n99\n82\n76\n64\n63\n68\n64\n67\n71\n72\n89\n114\n102\n85\n88\n97\n94\n88\n79\n74\n79\n95\n70\n72\n63\n60\n74\n75\n91\n126\n161\n109\n108\n110\n130\n166\n143\n103\n89\n76\n93\n82\n71\n69\n75\n134\n183\n113\n108\n121\n139\n109\n90\n88\n88\n93\n106\n89\n79\n91\n96\n111\n112\n104\n94\n98\n88\n94\n81\n77\n84\n92\n96\n1

In [82]:
#%% Get the content of a page using the requests library
import requests
#mywebpage_url='https://www.tuni.fi/en/'
mywebpage_url='https://homepages.tuni.fi/jaakko.peltonen/'
mywebpage_html=requests.get(mywebpage_url)
#%% Parse the HTML content using beautifulsoup
import bs4
mywebpage_parsed=bs4.BeautifulSoup(mywebpage_html.content,'html.parser')



In [83]:
mywebpage_parsed

<html>
<head>
<link href="jpeltonen_ver3.css" rel="stylesheet" type="text/css"/>
<title>Jaakko Peltonen</title>
<meta content="Professor of statistics (data analysis) at Tampere University. Researcher in machine learning, exploratory data analysis, visualization, and learning from multiple sources" name="description"/>
<meta content="statistics, machine learning, exploratory data analysis, learning from multiple sources, visualization, dimensionality reduction, bioinformatics, learning metrics, Neighbor Retrieval Visualizer, neighborhood embedding, neighbor embedding, topic modeling, matrix factorization, game culture studies, Computational Big Data Analytics, CBDA, Data Science, DS, Statistical Data Analytics, SDA, Computing Sciences, relevant subtask learning" name="keywords"/>
<meta content="Jaakko Peltonen" name="author"/>
</head>
<body>
<table class="titlebar-table"><tr><td class="titlebar-cell"></td></tr></table>
<table class="allcontent">
<tr>
<td class="maincontent">
<table cla

In [11]:
#%% Get the text content of the page
def getpagetext(parsedpage):
    # Remove HTML elements that are scripts
    scriptelements=parsedpage.find_all('script')
    # Concatenate the text content from all table cells
    for scriptelement in scriptelements:
        # Extract this script element from the page.
        # This changes the page given to this function!
        scriptelement.extract()
    pagetext=parsedpage.get_text()
    return(pagetext)
mywebpage_text=getpagetext(mywebpage_parsed)
print(mywebpage_text)




Jaakko Peltonen














Jaakko Peltonen

I am a professor of statistics (data analysis) at Tampere University,
Faculty 
of Information Technology and Communication Sciences, 
unit of Computing Sciences and 
the statistical data analytics team within the unit.


I am the leader of the 
Statistical Machine Learning and Exploratory Data Analysis (SMiLE) research group
and a member of the 
Academy of Finland Center of Excellence in Game Culture Studies.


I am also a docent (adjunct professor) at Aalto University, 
where I have been a visiting professor at the 
Department of Computer Science,
and where I have been a PI of the 
Probabilistic Machine Learning 
research group; I was previously an academy research fellow at the same department. 
I have a previous webpage at Aalto.

I previously worked at University of Sheffield, 
Sheffield Institute for Translational Neuroscience, 
with Prof. 
Magnus Rattray and 
Prof. Neil Lawrence. 
I am a member of the Centre of Excellence in 
Comp

In [16]:
#%% Find linked pages in Finnish sites, but not PDF or PS files
def getpageurls(webpage_parsed):
 # Find elements that are hyperlinks
    pagelinkelements=webpage_parsed.find_all('a')
    pageurls=[];
    for pagelink in pagelinkelements:
        pageurl_isok=1
        try:
            pageurl=pagelink['href']
        except:
            pageurl_isok=0
        if pageurl_isok==1:
            # Check that the url does NOT contain these strings
            if (pageurl.find('.pdf')!=-1)|(pageurl.find('.ps')!=-1):
                pageurl_isok=0
            # Check that the url DOES contain these strings
            if (pageurl.find('http')==-1)|(pageurl.find('.fi')==-1):
                pageurl_isok=0
        if pageurl_isok==1:
            pageurls.append(pageurl)
    return(pageurls)



In [17]:
mywebpage_urls=getpageurls(mywebpage_parsed)
print(mywebpage_urls)

['https://www.tuni.fi/en', 'https://www.tuni.fi/en/about-us/faculty-information-technology-and-communication-sciences', 'https://www.tuni.fi/en/about-us/computing-sciences', 'http://cs.aalto.fi/en/', 'http://www.cis.hut.fi/projects/mi', 'http://users.ics.aalto.fi/jtpelto/', 'http://research.ics.aalto.fi/coin/', 'https://www.tuni.fi/studentsguide/curriculum/degree-programmes/uta-tohjelma-1717?year=2019', 'https://www.tuni.fi/en/study-with-us/computing-sciences-data-science?navref=curated--list', 'https://www.tuni.fi/en/study-with-us/computing-sciences-statistical-data-analytics?navref=curated--list', 'https://www.tuni.fi/studentsguide/curriculum/course-units/otm-d42bf3fb-ecd7-43ee-919e-3a18e0b7d885?year=2020&q=null', 'https://www.tuni.fi/studentsguide/curriculum/course-units/otm-386280c0-c76b-4837-b4e3-61a9d53130b4?year=2020', 'https://www.tuni.fi/studentsguide/curriculum/course-units/uta-ykoodi-48003?year=2019', 'https://www.tuni.fi/studentsguide/curriculum/course-units/uta-ykoodi-4801

In [84]:
def basicwebcrawler(seedpage_url,maxpages):
    # Store URLs crawled and their text content
    num_pages_crawled=0
    crawled_urls=[]
    crawled_texts=[]
    # Remaining pages to crawl: start from a seed page URL
    pagestocrawl=[seedpage_url]
    # Process remaining pages until a desired number
    # of pages have been found
    while (num_pages_crawled<maxpages)&(len(pagestocrawl)>0):
        # Retrieve the topmost remaining page and parse it
        pagetocrawl_url=pagestocrawl[0]
        print('Getting page:')
        print(pagetocrawl_url)
        pagetocrawl_html=requests.get(pagetocrawl_url)
        pagetocrawl_parsed=bs4.BeautifulSoup(pagetocrawl_html.content,'html.parser')
        # Get the text and URLs of the page
        pagetocrawl_text=getpagetext(pagetocrawl_parsed)
        pagetocrawl_urls=getpageurls(pagetocrawl_parsed)
        # Store the URL and content of the processed page
        num_pages_crawled=num_pages_crawled+1
        crawled_urls.append(pagetocrawl_url)
        crawled_texts.append(pagetocrawl_text)
        # Remove the processed page from remaining pages,
        # but add the new URLs
        pagestocrawl=pagestocrawl[1:len(pagestocrawl)]
        pagestocrawl.extend(pagetocrawl_urls)
    return(crawled_urls,crawled_texts, num_pages_crawled)

In [ ]:
#num_pages_crawled=0
crawled_urls=[]
crawled_texts=[]
def basicwebcrawler(seedpage_url,maxpages):
    # Store URLs crawled and their text content
    num_pages_crawled=0
    #crawled_urls=[]
    #crawled_texts=[]
    # Remaining pages to crawl: start from a seed page URL
    pagestocrawl=[seedpage_url]
    # Process remaining pages until a desired number
    # of pages have been found
    while (num_pages_crawled<maxpages)&(len(pagestocrawl)>0):
        # Retrieve the topmost remaining page and parse it
        pagetocrawl_url=pagestocrawl[0]
        print('Getting page:')
        print(pagetocrawl_url)
        pagetocrawl_html=requests.get(pagetocrawl_url)
        pagetocrawl_parsed=bs4.BeautifulSoup(pagetocrawl_html.content,'html.parser')
        # Get the text and URLs of the page
        pagetocrawl_text=getpagetext(pagetocrawl_parsed)
        pagetocrawl_urls=getpageurls(pagetocrawl_parsed)
        # Store the URL and content of the processed page
        num_pages_crawled=num_pages_crawled+1
        crawled_urls.append(pagetocrawl_url)
        crawled_texts.append(pagetocrawl_text)
        # Remove the processed page from remaining pages,
        # but add the new URLs
        pagestocrawl=pagestocrawl[1:len(pagestocrawl)]
        pagestocrawl.extend(pagetocrawl_urls)
        
        for page in pagestocrawl:
            basicwebcrawler(page, 10)
        
    return(crawled_urls,crawled_texts, num_pages_crawled)


In [ ]:
mycrawled_urls, mycrawled_texts, num_pages_crawled = basicwebcrawler('https://homepages.tuni.fi/jaakko.peltonen/', 10)

Getting page:
https://homepages.tuni.fi/jaakko.peltonen/
Getting page:
https://www.tuni.fi/en
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/ab

Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.

Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.

Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.

Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk
Getting page:
https://www.tuni.fi/en/about-us/tamk


In [1]:
mycrawled_urls


NameError: name 'mycrawled_urls' is not defined

In [109]:
num_pages_crawled

0

In [110]:
mycrawled_texts

['\n\n\nJaakko Peltonen\n\n\n\n\n\n\n\n\n\n\n\n\n\n\nJaakko Peltonen\n\nI am a professor of statistics (data analysis) at Tampere University,\nFaculty \nof Information Technology and Communication Sciences, \nunit of Computing Sciences and \nthe statistical data analytics team within the unit.\n\n\nI am the leader of the \nStatistical Machine Learning and Exploratory Data Analysis (SMiLE) research group\nand a member of the \nAcademy of Finland Center of Excellence in Game Culture Studies.\n\n\nI am also a docent (adjunct professor) at Aalto University, \nwhere I have been a visiting professor at the \nDepartment of Computer Science,\nand where I have been a PI of the \nProbabilistic Machine Learning \nresearch group; I was previously an academy research fellow at the same department. \nI have a previous webpage at Aalto.\n\nI previously worked at University of Sheffield, \nSheffield Institute for Translational Neuroscience, \nwith Prof. \nMagnus Rattray and \nProf. Neil Lawrence. \nI 

In [33]:
import nltk
sentenceSplitter=nltk.data.load('nltk:tokenizers/punkt/english.pickle')
sentenceSplitter.tokenize("E.g., J. Smith knows... and I know. But do you?")

['E.g., J. Smith knows... and I know.', 'But do you?']

In [34]:
#%% Tokenize loaded texts and change them to NLTK format
import nltk
mycrawled_nltktexts=[]
for k in range(len(mycrawled_texts)):
    temp_tokenizedtext=nltk.word_tokenize(mycrawled_texts[k])
    temp_nltktext=nltk.Text(temp_tokenizedtext)
    mycrawled_nltktexts.append(temp_nltktext)

In [36]:
mycrawled_nltktexts[2]

<Text: Faculty of Information Technology and Communication Sciences |...>

In [37]:
mycrawled_nltktexts

[<Text: Jaakko Peltonen Jaakko Peltonen I am a professor...>,
 <Text: Front page | Tampere universities Skip to main...>,
 <Text: Faculty of Information Technology and Communication Sciences |...>,
 <Text: Computing Sciences | Tampere universities Skip to main...>,
 <Text: Department of Computer Science | Aalto University Skip...>,
 <Text: Probabilistic Machine Learning Aalto.fi sci.aalto.fi cs.aalto.fi Probabilistic Machine...>,
 <Text: Jaakko Peltonen Aalto.fi sci.aalto.fi cs.aalto.fi Jaakko Peltonen Jaakko...>,
 <Text: COIN Aalto.fi sci.aalto.fi ics.tkk.fi COIN wiki Home Centre...>,
 <Text: Loading Student 's Guide & Curriculum...>,
 <Text: Data Science , Computing Sciences | Tampere universities...>]

In [39]:
#%% Make all crawled texts lowercase
mycrawled_lowercasetexts=[]
for k in range(len(mycrawled_nltktexts)):
    temp_lowercasetext=[]
    for l in range(len(mycrawled_nltktexts[k])):
        lowercaseword=mycrawled_nltktexts[k][l].lower()
        temp_lowercasetext.append(lowercaseword)
    temp_lowercasetest=nltk.Text(temp_lowercasetext)
    mycrawled_lowercasetexts.append(temp_lowercasetext)

In [40]:
mycrawled_lowercasetexts[0][1]

'peltonen'

In [42]:
#%% Stem the loaded texts
stemmer=nltk.stem.porter.PorterStemmer()
def stemtext(nltktexttostem):
    stemmedtext=[]
    for l in range(len(nltktexttostem)):
        # Stem the word
        wordtostem=nltktexttostem[l]
        stemmedword=stemmer.stem(wordtostem)
        # Store the stemmed word
        stemmedtext.append(stemmedword)
    return(stemmedtext)

mycrawled_stemmedtexts=[]
for k in range(len(mycrawled_lowercasetexts)):
    temp_stemmedtext=stemtext(mycrawled_lowercasetexts[k])
    temp_stemmedtext=nltk.Text(temp_stemmedtext)
    mycrawled_stemmedtexts.append(temp_stemmedtext)


In [43]:
mycrawled_stemmedtexts[0][9]

'statist'

In [44]:
nltk.download('tagsets')
nltk.help.upenn_tagset()

[nltk_data] Downloading package tagsets to
[nltk_data]     C:\Users\tunde\AppData\Roaming\nltk_data...


$: dollar
    $ -$ --$ A$ C$ HK$ M$ NZ$ S$ U.S.$ US$
'': closing quotation mark
    ' ''
(: opening parenthesis
    ( [ {
): closing parenthesis
    ) ] }
,: comma
    ,
--: dash
    --
.: sentence terminator
    . ! ?
:: colon or ellipsis
    : ; ...
CC: conjunction, coordinating
    & 'n and both but either et for less minus neither nor or plus so
    therefore times v. versus vs. whether yet
CD: numeral, cardinal
    mid-1890 nine-thirty forty-two one-tenth ten million 0.5 one forty-
    seven 1987 twenty '79 zero two 78-degrees eighty-four IX '60s .025
    fifteen 271,124 dozen quintillion DM2,000 ...
DT: determiner
    all an another any both del each either every half la many much nary
    neither no some such that the them these this those
EX: existential there
    there
FW: foreign word
    gemeinschaft hund ich jeux habeas Haementeria Herr K'ang-si vous
    lutihaw alai je jour objets salutaris fille quibusdam pas trop Monte
    terram fiche oui corporis ...
IN: preposition or

[nltk_data]   Unzipping help\tagsets.zip.


In [45]:
#%% Convert a POS tag for WordNet
def tagtowordnet(postag):
    wordnettag=-1
    if postag[0]=='N':
        wordnettag='n'
    elif postag[0]=='V':
        wordnettag='v'
    elif postag[0]=='J':
        wordnettag='a'
    elif postag[0]=='R':
        wordnettag='r'
    return(wordnettag)

In [46]:
#%% POS tag and lemmatize the loaded texts
# Download tagger and wordnet resources if you do not have them already
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
lemmatizer=nltk.stem.WordNetLemmatizer()

def lemmatizetext(nltktexttolemmatize):
    # Tag the text with POS tags
    taggedtext=nltk.pos_tag(nltktexttolemmatize)
    # Lemmatize each word text
    lemmatizedtext=[]
    for l in range(len(taggedtext)):
        # Lemmatize a word using the WordNet converted POS tag
        wordtolemmatize=taggedtext[l][0]
        wordnettag=tagtowordnet(taggedtext[l][1])
        if wordnettag!=-1:
            lemmatizedword=lemmatizer.lemmatize(wordtolemmatize,wordnettag)
        else:
            lemmatizedword=wordtolemmatize
        # Store the lemmatized word
        lemmatizedtext.append(lemmatizedword)
    return(lemmatizedtext)

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\tunde\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\tunde\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


In [48]:
mycrawled_lemmatizedtexts=[]
for k in range(len(mycrawled_lowercasetexts)):
    lemmatizedtext=lemmatizetext(mycrawled_lowercasetexts[k])
    lemmatizedtext=nltk.Text(lemmatizedtext)
    mycrawled_lemmatizedtexts.append(lemmatizedtext)

In [51]:
mycrawled_lemmatizedtexts[0][9]

'statistic'

In [52]:
#%% Find the vocabulary, in a distributed fashion
import numpy
myvocabularies=[]
myindices_in_vocabularies=[]
# Find the vocabulary of each document
for k in range(len(mycrawled_lemmatizedtexts)):
    # Get unique words and where they occur
    temptext=mycrawled_lemmatizedtexts[k]
    uniqueresults=numpy.unique(temptext,return_inverse=True)
    uniquewords=uniqueresults[0]
    wordindices=uniqueresults[1]
    # Store the vocabulary and indices of document words in it
    myvocabularies.append(uniquewords)
    myindices_in_vocabularies.append(wordindices)
    
myvocabularies[0]

array(['!', '$', '&', ..., 'ziyuan', '©', 'âkerlund'], dtype='<U31')

In [53]:
# Unify the vocabularies.
# First concatenate all vocabularies
tempvocabulary=[]
for k in range(len(mycrawled_lemmatizedtexts)):
    tempvocabulary.extend(myvocabularies[k])
# Find the unique elements among all vocabularies
uniqueresults=numpy.unique(tempvocabulary,return_inverse=True)
unifiedvocabulary=uniqueresults[0]
wordindices=uniqueresults[1]
# Translate previous indices to the unified vocabulary.
# Must keep track where each vocabulary started in
# the concatenated one.
vocabularystart=0
myindices_in_unifiedvocabulary=[]
for k in range(len(mycrawled_lemmatizedtexts)):
# In order to shift word indices, we must temporarily
# change their data type to a Numpy array
    tempindices=numpy.array(myindices_in_vocabularies[k])
    tempindices=tempindices+vocabularystart
    tempindices=wordindices[tempindices]
    myindices_in_unifiedvocabulary.append(tempindices)
    vocabularystart=vocabularystart+len(myvocabularies[k])

In [55]:
unifiedvocabulary[3693:10000]

array(['tamk', 'tamkget', 'tampere', 'tampere1', 'tamperel', 'tanja',
       'tapani', 'tapeout', 'tapio', 'target', 'tarmo', 'tase', 'task',
       'tat-seng', 'tatjana', 'tauchi', 'taught', 'tavakoli', 'tb109',
       'tc13', 'teach', 'teacher', 'teaching', 'team', 'tech',
       'technical', 'technique', 'technologie', 'technology', 'teddy',
       'tejas', 'tek', 'tekes', 'tekniikan', 'tekniska',
       'teknologiateollisuus', 'telecomunicacoes', 'telephone',
       'temporal', 'tenure-track', 'tenured', 'teppo', 'terhi', 'term',
       'teräs', 'test', 'test-bench', 'testimonial', 'text',
       'text-mining-driven', 'tfif', 'than', 'that', 'the', 'theatre',
       'their', 'them', 'thematically', 'theme', 'then', 'theophilos',
       'theoretic', 'theoretical', 'theory', 'therapy', 'there',
       'therefore', 'these', 'thesis', 'they', 'thing', 'thinking',
       'third', 'thirty-fourth', 'this', 'thomas', 'thong', 'those',
       'thousand', 'three', 'three-year', 'through', 't

In [56]:
myindices_in_unifiedvocabulary

[array([2180, 2937, 2180, ..., 3874,  932, 2181], dtype=int64),
 array([1745, 2888, 4150, ..., 3695, 3910, 1081], dtype=int64),
 array([1637, 2807, 2076, ..., 3695, 3910, 1081], dtype=int64),
 array([1111, 3385, 4150, ..., 3695, 3910, 1081], dtype=int64),
 array([1291, 2807, 1112, ..., 3632, 3654, 1509], dtype=int64),
 array([3092, 2473, 2380, ...,  932, 3011, 1854], dtype=int64),
 array([2180, 2937,  531, ..., 3794, 1370, 1673], dtype=int64),
 array([1053,  531, 3383, 2007, 1053, 4067, 1947,  976, 2807, 1585, 3135,
        2210, 2843, 1139, 3746, 1693,  976, 2807, 1585, 2045, 1109, 2068,
        3263,    9, 1053,   10, 3746, 1693,  976, 2807, 1585, 2045, 1109,
        2068, 3263,    9, 1053,   10, 1307, 2584, 1722, 3837, 3746, 1241,
        3100,  932, 3746, 1210, 1241, 3286, 2131, 3931, 2076,   28, 3746,
        2289, 2585, 1722,  559, 3767, 1823,  832, 3573,  669, 1109, 2068,
         824, 2825, 3746, 1241,   28, 3746, 1487,  832, 2825, 2360, 1241,
        1061,  669, 1110, 1283, 26

### Basic Word Statistics and Vocabulary Pruning

In [ ]:
# First pass: count occurrences
for k in range(len(mycrawled_lemmatizedtexts)):
    print(k)
    occurrencecounts = numpy.zeros((len(unifiedvocabulary),1))
    for l in range(len(myindices_in_unifiedvocabulary[k])):
        occurrencecounts[myindices_in_unifiedvocabulary[k][l]] = occurrencecounts[myindices_in_unifiedvocabulary[k][l]] + 1
    unifiedvocabulary_totaloccurrencecounts = unifiedvocabulary_totaloccurrencecounts + occurrencecounts
    unifiedvocabulary_documentcounts = unifiedvocabulary_documentcounts + (occurrencecounts>0)


In [ ]:
# Mean occurrence counts over documents
unifiedvocabulary_meancounts = unifiedvocabulary_totaloccurrencecounts/len(mycrawled_lemmatizedtexts)

In [ ]:
# Second pass to count variances
for k in range(len(mycrawled_lemmatizedtexts)):
    print(k)
    occurrencecounts=numpy.zeros((len(unifiedvocabulary),1))
    for l in range(len(myindices_in_unifiedvocabulary[k])):
    occurrencecounts[myindices_in_unifiedvocabulary[k][l]]= \
    occurrencecounts[myindices_in_unifiedvocabulary[k][l]]+1
    unifiedvocabulary_countvariances=unifiedvocabulary_countvariances+ \
    (occurrencecounts-unifiedvocabulary_meancounts)**2
unifiedvocabulary_countvariances = unifiedvocabulary_countvariances/(len(mycrawled_lemmatizedtexts)-1)

In [ ]:
#%% Inspect frequent words
# Sort words by largest total (or mean) occurrence count
highest_totaloccurrences_indices=numpy.argsort(-1*unifiedvocabulary_totaloccurrencecounts,axis=0)
print(numpy.squeeze(unifiedvocabulary[highest_totaloccurrences_indices[1:100]]))
print(numpy.squeeze(unifiedvocabulary_totaloccurrencecounts[\
highest_totaloccurrences_indices[1:100]]))

In [57]:
# download the stopword list if you do not have it already
nltk.download('stopwords')
print(nltk.corpus.stopwords.words('english'))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tunde\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

In [79]:
x=["tunde"]

In [81]:
len(x)

1

Crawl:  https://homepages.tuni.fi/jaakko.peltonen/


NameError: name 'requests' is not defined