#### Exercise 11.3

In [1]:
import nltk
import numpy as np
import gensim

C:\Users\tunde\anaconda3\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [2]:
temp_file = open('hmm_sentences.txt','r', encoding='utf-8', errors='ignore')
text_lines = temp_file.readlines()
temp_file.close()

In [3]:
len(text_lines)

1000

In [4]:
hmm_sentences = []
for line in text_lines:
    temp_text = line.strip()
    temp_text = ' '.join(temp_text.split())
    hmm_sentences.append(temp_text)

In [5]:
len(hmm_sentences)

1000

In [6]:
# Tokenize downloaded texts and change them to NLTK format
mydownloaded_nltk_texts = []
for k in range(len(hmm_sentences)):
    temp_tokenizedtext = nltk.word_tokenize(hmm_sentences[k])
    temp_nltktext = nltk.Text(temp_tokenizedtext)
    mydownloaded_nltk_texts.append(temp_nltktext)

In [7]:
len(mydownloaded_nltk_texts)

1000

In [8]:
# Make all downloaded texts lowercase
mydownloaded_lowercase_texts = []
for k in range(len(mydownloaded_nltk_texts)):
    temp_lowercase_text = []
    for l in range(len(mydownloaded_nltk_texts[k])):
        lowercase_word = mydownloaded_nltk_texts[k][l].lower()
        temp_lowercase_text.append(lowercase_word)
    temp_lowercasetest = nltk.Text(temp_lowercase_text)
    mydownloaded_lowercase_texts.append(temp_lowercase_text)

In [9]:
mydownloaded_lowercase_texts[0]

['where', 'may', 'you', 'feed', '?']

In [10]:
gensim_sentences = mydownloaded_lowercase_texts
word2vecmodel = gensim.models.word2vec.Word2Vec(sentences=gensim_sentences, vector_size=5, window=3, 
                                               min_count=1, workers=4, sg=0)


In [11]:
word2vecmodel.wv['where']

array([-0.3532374 ,  0.97565985,  0.6355194 , -0.6277016 ,  0.7025194 ],
      dtype=float32)

In [12]:
word2vecmodel.wv['dog']

array([-0.10362475,  1.0357132 ,  0.5709109 , -0.32588273,  0.71481293],
      dtype=float32)

In [13]:
word2vecmodel.wv['explain']

array([-0.09376109,  1.0055654 ,  0.82805413, -0.2995348 ,  0.7795933 ],
      dtype=float32)